[package]
name = "SlintWrapper"
version = "0.1.0"
edition = "2021"
authors = ["oheil <git@heilbit.de>"]
build="build/build.rs"

[dependencies]
slint = "1.11.0"
slint-interpreter = { version = "1.11.0", features = ["display-diagnostics"] }
spin_on = "0.1.1"
once_cell = "1.21.3"
log = "0.4.27"
env_logger = "0.11.8"
plotters = "0.3.7"

[lib]
name = "slintwrapper"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.29"
regex = "1.11"
