import { Button, VerticalBox } from "std-widgets.slint";

//export global Logic {
//    pure callback button-clicked();
    // You can collect other global properties here
//}

export component Demo inherits Window {
    //callback button-clicked(string);
    callback button-clicked();
    VerticalBox {
        alignment: start;
        t1 := Text {
            text: "Hello World!";
            font-size: 2rem;
            horizontal-alignment: center;
        }
        HorizontalLayout {
            alignment: center;
            Button {
                text: "OK";
                //clicked => {root.button-clicked(t1.text);}
                clicked => {root.button-clicked();}
            }
        }
    }
}
