// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { LineEdit, Button, Slider, StandardListView, GridBox, HorizontalBox } from "std-widgets.slint";

struct SlintValue  { value_s: string, value_i: int, value_f: float }

export component MainWindow inherits Window {
    //in property <[StandardListViewItem]> names-list;
    in-out property <[[StandardListViewItem]]> names-list;

    //in-out property <[[SlintValue]]> names-list-bridge;

    //callback bridge2StandardListViewItem( string,string );
    //callback bridge2StandardListViewItem( [[SlintValue]], [StandardListViewItem] );
    //changed names-list-bridge => {
        //bridge2StandardListViewItem(names-list-bridge,names-list);
        //bridge2StandardListViewItem("names-list-bridge","names-list");
    //}

    out property <int> current-item: list.current-item;
    out property <string> name;
    out property <string> surname;
    out property <string> prefix;
    callback prefixEdited();
    callback createClicked();
    callback updateClicked();
    callback deleteClicked();

    GridBox {
        Text {
            text: "Filter prefix:";
            vertical-alignment: center;
            horizontal-alignment: right;
        }

        LineEdit {
            text <=> root.prefix;
            edited => { root.prefixEdited() }
        }

        list := StandardListView {
            row: 1;
            rowspan: 3;
            colspan: 2;
            model: root.names-list[0];

        }

        Text {
            col: 2;
            row: 1;
            text: "Name: ";
            vertical-alignment: center;
            horizontal-alignment: right;
        }

        LineEdit { text <=> root.name; }

        Text {
            col: 2;
            row: 2;
            text: "Surname: ";
            vertical-alignment: center;
            horizontal-alignment: right;
        }

        LineEdit { text <=> root.surname; }

        HorizontalBox {
            padding-left: 0;
            padding-bottom: 0;
            row: 4;
            alignment: start;

            Button {
                clicked => { root.createClicked() }

                text: "Create";
            }
            Button {
                clicked => { root.updateClicked() }

                text: "Update";
                enabled: list.current-item != -1 && list.current-item < root.names-list[0].length;
            }
            Button {
                clicked => { root.deleteClicked() }

                text: "Delete";
                enabled: list.current-item != -1 && list.current-item < root.names-list[0].length;
            }
        }
    }
}
